### ISSUE TITLE
Show modal when navigation is blocked in Participate view

### ISSUE THREAD

**Issue by MartijnR** [OpenClinica/enketo-express-oc#114]

**Comment by MartijnR** [comment]
on hold to tweak modal texts

**Comment by pbowen-oc** [comment]
@MartijnR - Can you update the popup message for blocked form navigation due to strict checks (Next button or Close button) to use the text in the attached image?

Can you make the popup text black (not white as is shown here)? Can you also try making the orange color we are using for strict errors (popup and on-form) a paler shade?

![revised_patient_facing_error_end_of_page_-_color_1](https://user-images.githubusercontent.com/25179620/45894869-ade85600-bd9d-11e8-8b97-1906ac23ba2d.png)

**Comment by pbowen-oc** [comment]
@MartijnR - Related to the above request for black text in the popup, can you also make the current regular view popup that occurs when I click Complete when there any error messages also use black text?

A screenshot of the current popup is attached.

![2018-09-21 12_58_12-openclinica](https://user-images.githubusercontent.com/25179620/45895031-20593600-bd9e-11e8-81bb-4ceec2c94f01.png)

**Comment by MartijnR** [comment]
also no countdown timer

**Comment by MartijnR** [comment]
* [ ] change orange color
* [ ] change all error text color in modal
* [ ] change texts in Close modal
* [ ] change text in nav-block modal
* [ ] remove timer from nav-block modal
