### ISSUE TITLE
Dynamic code label text does not appear in the first repeat

### ISSUE THREAD

**Issue by pbowen-oc** [OpenClinica/enketo-express-oc#178]
In the attached form, the code labels have dynamic text. The first repeat does not show the dynamic text. Subsequent repeats do show the dynamic text as seen in the screenshot.
[repeating group with dynamic code label text.xml.txt](https://github.com/OpenClinica/enketo-express-oc/files/2933269/repeating.group.with.dynamic.code.label.text.xml.txt)
![2019-03-05 16_48_00-openclinica](https://user-images.githubusercontent.com/25179620/53839984-e4d6b080-3f66-11e9-9685-aa72a0daf9a1.png)

**Comment by MartijnR** [comment]
http://localhost:8005/?xform=repeating.dynamic.label.xml

**Comment by MartijnR** [comment]
There is a way to fix this particular form, quickly and easily without breaking tests. However, this is not a fix, because outputs are not updated when they should. E.g. if SRG01 question because a form control, it will not update the itemsets when the user changes the value. So you get something like this:

<img width="846" alt="screen shot 2019-03-06 at 4 13 50 pm" src="https://user-images.githubusercontent.com/627350/53920573-d9e55400-402a-11e9-8bcc-5c2ac9acfbdf.png">

**Comment by MartijnR** [comment]
Any fix would not work with select minimal (currently already the case).

**Comment by pbowen-oc** [comment]
@MartijnR - What is the quick way to update to make this specific form work? The actual use case for this form is that the values are read in from our external data file, so we don't expect them to change during the course of data entry on the form.

**Comment by MartijnR** [comment]
It's a matter of moving a line of code. It sounds like I should just do that perhaps without fixing dynamic outputs (in labels) of itemsets.
