### ISSUE TITLE
Firefox - Date function generates date 1 day off

### ISSUE THREAD

**Issue by pbowen-oc** [OpenClinica/enketo-express-oc#233]
Issue #197 fixed a bug where using the date(concat(string)) function produced a result that was 1 day off from what was expected. The fix in #197 resolved that for Chrome.

However, we have found that the same apparent issue currently exists in Firefox.
[Diagnosis_4 (1).xlsx](https://github.com/OpenClinica/enketo-express-oc/files/3419385/Diagnosis_4.1.xlsx)
<img width="711" alt="off by 1 day" src="https://user-images.githubusercontent.com/25179620/61669967-f0293f00-acaf-11e9-8fe0-9e4c1ae9139d.png">

**Comment by MartijnR** [comment]
* [ ] create simpler form that passes ODK Validate : https://docs.google.com/spreadsheets/d/1j8Kl3SMt5PatV5Ftf83S9NXVz2BqpyeMNoPaT0KZbAc/edit?usp=sharing
* [ ] reproduce in Enketo Core
* [ ] figure out if same as #197
* [ ] run enketo-xpathjs tests in FF

**Comment by MartijnR** [comment]
Safari on MacOS does not create a date (invalid) at all. This is caused by the lack of tolerance for unpadded months ('9' instead of '09').

**Comment by MartijnR** [comment]
@pbowen-oc, FF does a correction for us and thinks that's helpful. While investigating the issue in Safari, I accidentally found that providing a (proper) padded month (and year and day, though there is no risk of providing an unpadded year and day in your form), both issues get resolved.

Rather than changing Enketo code (which will be very challenging as we'll be fighting native browser Date object implementations), I think that is the way to deal with this. The main argument is that an unpadded month would strictly speaking [not comply with our spec](https://opendatakit.github.io/xforms-spec/#data-types). 

For the workaround, see https://docs.google.com/spreadsheets/d/1j8Kl3SMt5PatV5Ftf83S9NXVz2BqpyeMNoPaT0KZbAc/edit?usp=sharing.

It doesn't matter whether you wrap BEGIN7 in a `date()` or not, so I kept everything as simple as possible, taking into account how XPath automatically converts when necessary.

(PS. looks like calc for month 7 is actually for month 17)

**Comment by pbowen-oc** [comment]
This is working as expected when we manually pad the date values to be in the expected format.
