### ISSUE TITLE
Sometimes defaultAssignee is not determined correctly in DN widget

### ISSUE THREAD

**Issue by MartijnR** [OpenClinica/enketo-express-oc#273]
No defaultAssignee. Not sure why.

**Comment by theywa** [comment]
Based on current logic(CMIIW), 'usersOptionsHtml' variable for assign to dropdown is set as a global variable that will be set based on the first item(not sure how to determine the first item, sometimes the first item on the form, not the first one that loaded) and used for all items. Since it's only set just once then if the first item doesn't contain any comment then no default user will be set for all items.
So to fix that, I change 'usersOptionsHtml' to a local variable so default user will be set for each item not set for all items.

**Comment by MartijnR** [comment]
👍 Wow, that bug must have been present forever. Will review PR.

**Comment by pbowen-oc** [comment]
Passed testing.
