### ISSUE TITLE
VAS item broken

### ISSUE THREAD

**Issue by pbowen-oc** [OpenClinica/enketo-express-oc#342]
In our OC3 build (2.3.0.oc-1), analog scale items are not working as before. 

![Annotation 2020-06-09 171219](https://user-images.githubusercontent.com/25179620/84203435-6cb73e80-aa77-11ea-8064-e6edd358fda0.png)

Here is the XForm for that:
[OC3 XForm VAS broken.xml.txt](https://github.com/OpenClinica/enketo-express-oc/files/4754972/OC3.XForm.VAS.broken.xml.txt)

Since we need to get this working again ASAP, we'd like to get a fix built from that same branch:
![Annotation 2020-06-09 172631](https://user-images.githubusercontent.com/25179620/84203534-9c664680-aa77-11ea-8278-c867c9d39d2a.png)

Note that this item/form works as expected on the very old version we were running before. It also works as expected on our current OC4 Prod version (1.85.x) and current OC4 Dev version (which is running the latest from master).

**Comment by MartijnR** [comment]
Will check it out asap. In the mean time, this looks exactly like what one would see if 'analog-scale' wasn't added to the `widgets` item in config.json. It looks like just a regular text field. This widget is present in default-config.json in `2.3.0.oc-1`, so that would be the cause if config.json overwrites the `widgets` item without `analog-scale` as part of the array.

Since this is OC3, and the version doesn't show `2.3.0.oc-1`, it might be that you're running the regular non-OC enketo (which doesn't have analog-scale in default-config.json)

* [ ] check if I can reproduce in `2.3.0.oc-1`

P.S. we really need to figure out how to properly display the version in OC.

**Comment by pbowen-oc** [comment]
Analog-scale was missing, so it looks like that was issue. Thanks for looking into this. I'll let you know if we run into any other issues.
