### ISSUE TITLE
loading performance of form sent by email on 6/24

### ISSUE THREAD

**Issue by MartijnR** [OpenClinica/enketo-express-oc#352]
high priority

**Comment by MartijnR** [comment]
http://localhost:8005/single/fs/i/3izKuKeE?ecid=1

**Comment by MartijnR** [comment]
* [ ] compare XForms

**Comment by pbowen-oc** [comment]
@MartijnR - Do you see anything that might be done to optimize the form itself (the one I sent that was created in the old Pyxform for 1.85.1.oc-1)? When opening a new form, I get results a little slower than what you reported (possibly due to the work done on our end to call Enketo). However, when opening an existing record with an instance containing data for about 50 items (just from the automatically calculated values), it is 15-20 seconds slower. This is despite the browser reporting that the initial calls to open the form are the same about (2-3 seconds total).

**Comment by MartijnR** [comment]
I'm not even close to reaching that stage. Still figuring out the clear Enketo issue. Getting close to that. Note that the comments above are continuously updated as I progress.

**Comment by MartijnR** [comment]
Oddly, while investigating #353, I'm now finding the old pyxform form loads in 7 seconds without a record and the new pyxform form loads in 10 seconds without a record. This is very weird.

**Comment by MartijnR** [comment]
changing getTemplates to force use the native evaluator eliminates any slowdown caused by static defaults.

**Comment by MartijnR** [comment]
Biggest chunk of this work is now done in latest master `2.3.7.oc-1`

**Comment by pbowen-oc** [comment]
@MartijnR - The performance generally seems much better on the forms I could test successfully.

However, the original form I sent on 6/24 is not working correctly. I am running the same form definition since 6/24 (no subsequent XLS upload/Pyxform conversion).

When I open the form, an item that should be non-relevant by default shows an error despite the relevant condition not being met with an empty form. See here:
![Annotation 2020-07-29 014421](https://user-images.githubusercontent.com/25179620/88762106-85220c00-d13e-11ea-8e33-2424b3754e44.png)

When the form loads, I see these errors in the console:
![Annotation 2020-07-29 014342](https://user-images.githubusercontent.com/25179620/88762144-9ff48080-d13e-11ea-8bea-a32bb1759b0b.png)

Note that I also tried opening a new mini-version of this form with just these first few items and the result is the same.

**Comment by pbowen-oc** [comment]
Further testing shows that this is also happening on other forms for all date items that have relevant conditions (at least for ones based on select_one items).

**Comment by MartijnR** [comment]
* [x] reproduce in enketo-express-oc - yes
* [ ] reproduce in enketo-core

**Comment by MartijnR** [comment]
moved to https://github.com/OpenClinica/enketo-express-oc/issues/366

**Comment by pbowen-oc** [comment]
Looks good after testing.
