### ISSUE TITLE
default expression (dynamic) without form control (and without calculation) not working

### ISSUE THREAD

**Issue by MartijnR** [OpenClinica/enketo-express-oc#355]
https://docs.google.com/spreadsheets/d/19GYXObKfxtywLlbJ1F4r9ovtehlrQBD_2u5SwC2wN4w/edit#gid=0 (question one)

**Comment by MartijnR** [comment]
working in hand-crafted XForm: http://localhost:8005/?xform=setvalue.xml (question /data/a)

* [ ] check pyxform output for possible bug

**Comment by MartijnR** [comment]
I believe this was fixed in pyxform. To be tested in forthcoming 1.1.1 or 1.2.0 release (whichever is first)

**Comment by pbowen-oc** [comment]
@MartijnR - It looks like I can set a calculate item to have a dynamic default with a function without also having a calculation. However, other items with defaults that reference the calculate item fail to get the default value as expected when opened in Enketo. This issue seems specific to having a source item of type calculate.

[default test.xml.txt](https://github.com/OpenClinica/enketo-express-oc/files/5456120/default.test.xml.txt)

Also, if I have calculate item with a default that is a reference to another item, that fails to convert in Pyxform and I get an error like this:
Traceback (most recent call last): File "/opt/transformer/XLSForm-repo/src/pyxform/pyxform/xls2xform.py", line 195, in main_cli() File "/opt/transformer/XLSForm-repo/src/pyxform/pyxform/xls2xform.py", line 177, in main_cli enketo=args.enketo_validate, File "/opt/transformer/XLSForm-repo/src/pyxform/pyxform/xls2xform.py", line 49, in xls2xform_convert enketo=enketo, File "/opt/transformer/XLSForm-repo/src/pyxform/pyxform/survey.py", line 933, in print_xform_to_file raise error KeyError: 'calculate'

**Comment by MartijnR** [comment]
* [ ] fix http://localhost:8005/?xform=dynamic-default-simple-node-ref.xml - check order of setvalue calculations
* [ ] investigate pyxform error

**Comment by MartijnR** [comment]
The fix is a little complicated. The issue is dependent on the order in which the setvalue/odk-instance-first-load calculations get evaluated. We could simply run the calculations twice but it will still be an issue with a chain of more than 2 dependent dynamic defaults.

Another issue with running the calculations twice is if e.g. a random number is generated without using once() (which is very likely since once() would normally be obsolete for a dynamic default), and it is used by a dependent question during the first dynamic default calculation iteration, its value would change in the subsequent iteration (which may be using once()).

With OC you'd also record multiple values in the question history.

**Comment by MartijnR** [comment]
Perhaps we can do something with the assumptions that an empty result of a dynamic default is unlikely to be desired. Or slightly different, that a non-empty result shouldn't be run again.

**Comment by pbowen-oc** [comment]
Let's consider always evaluating defaults for non-form control items first (in form order) and then form control items afterwards (in form order).

**Comment by MartijnR** [comment]
Do same with `odk-new-repeat` event

**Comment by pbowen-oc** [comment]
Looks good in testing.
