### ISSUE TITLE
Add Vertical VAS appearance to show labels every 10 units

### ISSUE THREAD

**Issue by pbowen-oc** [OpenClinica/enketo-express-oc#359]
We need to support an analog-scale vertical appearance option to show numeric labels every 10 units to the left of the scale as shown:
![EQ5D Vertical VAS sample](https://user-images.githubusercontent.com/25179620/87272237-9c58cc80-c4a3-11ea-9f3b-4e7755f7a004.png)

We need to keep the existing behavior as it is now, so this should be a new appearance option. perhaps something like ~~"analog-scale vertical show-labels"~~ "analog-scale vertical show-scale". This will only be needed for the vertical widget and it would not be compatible with using the "no-ticks" appearance.

**Comment by MartijnR** [comment]
* [ ] move widget to fork
* [ ] add guidance for implementer

**Comment by MartijnR** [comment]
[This form](https://docs.google.com/spreadsheets/d/17o39y0iBpqBm4gywz67HAqfvGofViy5tr7hUuSpxSus/edit#gid=0) covers a lot of the different analog scale appearances using the traditional method with `type="integer"` (we didn't have type=range when this was initially developed). The alternative (and more modern) way of using this widget is with `type="range"` as shown [here](https://docs.google.com/spreadsheets/d/1C4cIy-PrhYTCFFawivlUvoQWF7ehdo1SIWbSLikdfRk/edit#gid=0). For this widget the differences between Grid and non-Grid themes usually requires particular attention.

This may be excessive guidance, but I'd do:

0. add new cases to test form with new appearance and with the unsupported no-ticks combination
1. convert the form on getodk/xlsform and add in enketo-core to /test/temp
2. run form locally on http://localhost:8005/?xform=analog-scale.xml
3. switch manually between themes by commenting/out stylesheet lines in /public/build/index.html
4. check out print styles (for each theme) by calling dev helpers (that are in app.js) in browser console: `printView()` and `printGridView()` (when Grid theme has been loaded) and optionally switch back with `printView(false)` and `printGridView(false)`
5. Note that when used with type="range" there is no limit in what min and max values can be used, which complicates this feature. @pbowen-oc, should that be taking into account or does none of your users know about using a range type?
6. Keep any CSS additions/changes limited to `.or-appearance-analog-scale` to avoid side-effects elsewhere.


@pbowen-oc, what about using `show-scale` instead of `show-labels`. I think using "labels" is a bit confusing?

**Comment by pbowen-oc** [comment]
@MartijnR - Yes, "show-scale" looks better. I updated it in my original comment.

For type="range" items, they are not an issue now as we don't support them yet, but we will before too long. The requirement for this issue is very specific to matching the display in the original screenshot. I would think that a more general solution for "range" items would have somewhat different requirements (and should be out of scope for this issue).

**Comment by gushil** [comment]
Hi @MartijnR I'm working on this.

I've tried to follow your guidance, but I have some problems. Should I do the fix in this repository or enketo-core?

**Comment by MartijnR** [comment]
@gushil, this should all be done in enketo-core, and probably all [here](https://github.com/enketo/enketo-core/tree/master/src/widget/analog-scale)

**Comment by gushil** [comment]
Thanks @MartijnR working on it.

**Comment by gushil** [comment]
Initial implementation. More tests still required.

**Comment by MartijnR** [comment]
* [ ] wait till merge with enketo-express

**Comment by pbowen-oc** [comment]
Looks good.
