### ISSUE TITLE
No form loading error when external instance is not loaded

### ISSUE THREAD

**Issue by pbowen-oc** [OpenClinica/enketo-express-oc#376]
We had seen past cases (such as #335) where there was a form loading error when the clinicaldata instance was unable to be parsed correctly because of an encoding issue. The form loading error brought about intentional messaging, UI, and saving behavior to handle the error case.

I had assumed the same would occur if an external instance for a select_one_from_file item or pulldata function in a calcualtion were not loaded. However, in testing this, I intentionally didn't upload the CSV file referenced by those and the form loaded without any errors despite the failure to load the file.

I also tried an xml-external item to test a missing XML instance's behavior, however Enketo did not not attempt to load the instance at all in that case. We have never tried supporting xml-external items before, so I don't know if that as an issue on our end or not.

**Comment by MartijnR** [comment]
enketo-core:

* http://localhost:8005/?xform=calc_n_footprint_29.xml :ok:

**Comment by MartijnR** [comment]
@pbowen-oc, it looks this works for /single/fs/i views. What you're seeing may be caused by:

1. loading a different view perhaps
2. something on the OC side that perhaps lists any referred instances in the /xformsManifest even though they were not uploaded by the user (this would happen if the XForm is used to generate the xformsManifest instead of the uploaded files).

We could perhaps troubleshoot the second option live during a meeting.

**Comment by MartijnR** [comment]
Looks like the cause is likely the dummy content that the old pyxform added.

**Comment by MartijnR** [comment]
* [ ] consider showing errors to unresolvable external data src files, except in `?form=` previews

**Comment by MartijnR** [comment]
* [ ] show external file errors together with any form load errors, but still show the form (and disable submissions).

**Comment by pbowen-oc** [comment]
Looks good.
