### ISSUE TITLE
when opening form and automatically going to dn widget on an image-map question, the image map ends up in the dn modal

### ISSUE THREAD

**Issue by MartijnR** [OpenClinica/enketo-express-oc#378]
Looks like we should wait for widgets to be initialized before 'goto' opens the dn modal.

**Comment by pbowen-oc** [comment]
Here is an example:

![Annotation 2020-09-09 153800](https://user-images.githubusercontent.com/25179620/92645325-adab3300-f2b2-11ea-947a-89510be23cf7.png)

**Comment by MartijnR** [comment]
http://localhost:8005/single/fs/i/YYpM#//us_map

**Comment by MartijnR** [comment]
@pbowen-oc could you provide the XForm please?

**Comment by pbowen-oc** [comment]
@MartijnR - Here you go:
[vitals_27b.xform.txt](https://github.com/OpenClinica/enketo-express-oc/files/5204950/vitals_27b.xform.txt)

**Comment by MartijnR** [comment]
http://localhost:8005/single/fs/i/YHy0crqH?ecid=1

**Comment by theywa** [comment]
Hi @MartijnR ~ I found cause why the image-map printed on the widget comment, it's because this code 
`that.question.querySelector( '.option-wrapper' ).before( fragment );` 
on _addMarkup function at image-map.js. There will be more than one '.option-wrapper' when the comment widget loaded and because the comment widget loaded first then that selector will pick the element from that widget and append it before that element.
And to fixed that we need to modify the selector like this
`that.question.querySelector( 'div[class=option-wrapper]' ).before( fragment );`

that would fix the image map position but there is a new issue with the scroll to view the comment widget so I added a timeout to delay the comment widget.

**Comment by MartijnR** [comment]
That sounds promising! Could you perhaps post the DOM showing the multiple option-wrappers?

**Comment by theywa** [comment]
Sure, here the Inspect element ss
![full-inspect-mark](https://user-images.githubusercontent.com/13865076/107234531-5aeac880-6a56-11eb-96ae-545000c1fae7.png)

and here the ss from console testing
![console-inspect](https://user-images.githubusercontent.com/13865076/107234583-663df400-6a56-11eb-96d1-5f1e60fde8f1.png)

**Comment by pbowen-oc** [comment]
Looks good in testing.
