### ISSUE TITLE
IE11/Edge Legacy regression - no forms open

### ISSUE THREAD

**Issue by pbowen-oc** [OpenClinica/enketo-express-oc#388]
With the current build, no forms open in IE11 or Edge Legacy.
[IE11 test.xml.txt](https://github.com/OpenClinica/enketo-express-oc/files/5403431/IE11.test.xml.txt)

IE11 error:
![Screenshot 2020-10-19 124644](https://user-images.githubusercontent.com/25179620/96481439-82005e80-1209-11eb-8023-4f834b64fbba.png)

Edge Legacy error (from a different form):
![Edge-Win10-2018-10-22 2020-10-19 10-10-49](https://user-images.githubusercontent.com/25179620/96483131-fdfaa680-1209-11eb-9614-e8fe16cfb018.png)

**Comment by MartijnR** [comment]
Not yet able to reproduce but I do note an error in the XForm:

```xml
<instance id="_users" src="jr://file-csv/users.xml" />
```
The `src` attribute should be either `"jr://file-csv/users.csv"` or (preferred) `"jr://file/users.xml"`. 

* [ ] see if recent refactoring removed tolerance for this error

**Comment by pbowen-oc** [comment]
I found an XForm from mid-2019 that contains the following:
<instance id="_users" src="jr://file-csv/users.xml"/>

There is now a space before the last slash that wasn't there in this previous example, but that is the only difference I see.

**Comment by MartijnR** [comment]
Yes, this has been done incorrectly for a long time in OC. It's not the cause of the issue though.

**Comment by MartijnR** [comment]
Guidance to work on this:

* run XForm that has an `<instance>` with a `src` attribute in Enketo Express. E.g. the form that @pbowen-oc posted above.
* run Enketo Express (not enketo-expresss-oc)  in developer mode (`grunt develop`)
* check Edge Legacy developer console to find out in what line the exception occurs
* if no exceptions occurs, try running the same form in enketo-express-oc to reproduce (I'm guessing the issue is not related to OC's fork, but I may be wrong)
* fix either in Enketo Core or Enketo Express or Enketo Express OC

**Comment by pbowen-oc** [comment]
The fix seems to work for Edge Legacy but not IE11.

**Comment by theywa** [comment]
Hi @MartijnR, I tried running XForm from Paul's XML using enketo-express-oc preview like this " https://dewa.ngrok.io/preview?form=https%3A//dewa.ngrok.io/external-users.xml " on IE 11 and manually set the external instance on form-model.js but can't reproduce the error. Also tried using enketo-express but it can't loaded since IE11 belong to an outdated browser. Is that the correct way to run the XForm on enketo-express that you mention on guidance?

**Comment by MartijnR** [comment]
Hi @theywa,

I must have forgotten to send my earlier response to your question. Sorry about that!

Run `grunt develop-ie11` to run enketo-express-oc. You're right, it won't work in enketo-express.

I'm not sure about your preview method, because of how the instance is "set". The error may be circumvented in the method you used.

**Comment by theywa** [comment]
@MartijnR, yes I'm using that command to run enketo-express-oc. Is that another way to run that XML with an external file? I'm not sure how to create a form with an external file using https://kc.kobotoolbox.org that when downloaded will result in the XML similar to the one Paul used above.

**Comment by MartijnR** [comment]
Hi @theywa, one way is to create a form with a pulldata() expression. See xlsform.org.

But you could also first try:

* server_url: https://enketo-aggregate.appspot.com/
* form_id: exml

(There are a bunch more forms with external files listed [here](https://enketo-aggregate.appspot.com/formList). Search for "external")

**Comment by theywa** [comment]
Hi @MartijnR, thanks for the forms, I can reproduce the issue using that form, 
at first, it looks like this 
![error](https://user-images.githubusercontent.com/13865076/103781768-58690d80-5069-11eb-91cf-462af449d0c5.png)
then after update the code, the external file loaded normally
![edge](https://user-images.githubusercontent.com/13865076/103781881-720a5500-5069-11eb-9edf-37ab8cf2ba71.png)
![ie11](https://user-images.githubusercontent.com/13865076/103781886-733b8200-5069-11eb-8ac4-973cddce3329.png)

**Comment by pbowen-oc** [comment]
I'm seeing different errors for my forms in IE11:
![Screenshot 2021-01-07 092935](https://user-images.githubusercontent.com/25179620/103904730-a7478f00-50cb-11eb-9198-189f566de31b.png)

**Comment by theywa** [comment]
@MartijnR ~ is it okay to add a polyfill script to make CSS.escape works on IE11?
