### ISSUE TITLE
Repeat Group out of sync with set value/defaults

### ISSUE THREAD

**Issue by pbowen-oc** [OpenClinica/enketo-express-oc#413]
Steps:
1. Open this form - [repeat set value test3.xml.txt](https://github.com/OpenClinica/enketo-express-oc/files/5718970/repeat.set.value.test3.xml.txt)
2. Select Yes for the first item
3. Note the first repeat
4. Add another repeat

Expected:
I expected that bp_row would be defaulted to the correct positional oridinal for each row and that bp_pos would be defaulted/triggered to the correct text for each row.

Actual:
bp_row is not populated for row 1. bp_pos is populated into row 1 only when row 2 is added (but it adds the value expected for row 1). This process continues for subsequent rows.

![Screenshot 2020-12-19 010634](https://user-images.githubusercontent.com/25179620/102682526-2d8d4700-4198-11eb-98a7-c48a0a9afe25.png)

Note that this XForm is missing the comment item for bp_pos due to a bug in XForm creation on our end, but I think everything else is as expected in the XForm.

**Comment by MartijnR** [comment]
move to the top?

**Comment by MartijnR** [comment]
http://localhost:8005/single/fs/i/Rz6mZEEG?ecid=1

**Comment by MartijnR** [comment]
* [ ] fix bp_row value is not shown in view (it is okay in the model)
* [ ] fix the relevant error that is shown although no user-editable fields have a value (likely bp_pos is cleared somehow)

**Comment by MartijnR** [comment]
The formula for the dynamic default value for bp_pos is not working because of the context for `position(..)`. This is a difficult-to-explain issue that I hadn't realized before, but it basically is this:

"Using a relative path inside a triggered calculation likely won't do what the form designer expects. This is because the context of the triggered calculation is the trigger question, not the target question".

This seems correct, but very difficult to explain because Pyxform now determines whether to use relative paths for some ${node} references (though not used in this form).

**Comment by pbowen-oc** [comment]
It looks like there is still an issue with this (or maybe a related issue).

This form - [select multiple default in repeat.xml.txt](https://github.com/OpenClinica/enketo-express-oc/files/5768212/select.multiple.default.in.repeat.xml.txt) - with a select multiple item with a simple default does not populate correctly as more repeats are added. When the form is opened, the first repeat is populated as expected. When a second repeat is added, the select multiple item does not get populated. When a third repeat is added, the select multiple item in the second repeat gets populated. This continues with every second repeat added causing a previous repeat's select multiple item to be populated.

**Comment by MartijnR** [comment]
http://localhost:8005/single/fs/i/D7HsCbkh?ecid=1

**Comment by pbowen-oc** [comment]
Looks good in testing.
