### ISSUE TITLE
Opening form using repeat count in review-only mode attempts to delete the repeating groups

### ISSUE THREAD

**Issue by pbowen-oc** [OpenClinica/enketo-express-oc#421]
Open the attached form in review-only mode (for example, /edit/fs/dn/c/i/). The form only displays the first repeating group row (not the also the second one that is in the instance). There is a failed call that seems to be trying to delete the repeating group and the console shows the following for the queue: "All done with queue submission. Current remaining queue is {DELETE_0: FormData}". Since this is review-only mode, repeats should not be deleted. The repeat count value is in the instance so there shouldn't be any reason to delete any rows. It seems that only the first row in the repeating group is being displayed and the other are attempted to be deleted as if the repeat count value is not being processed.

XForm:
[repeatcount1.xml.txt](https://github.com/OpenClinica/enketo-express-oc/files/5799833/repeatcount1.xml.txt)

Instance:
[repeatcount1.instance.txt](https://github.com/OpenClinica/enketo-express-oc/files/5799834/repeatcount1.instance.txt)

![Screenshot 2021-01-11 234907](https://user-images.githubusercontent.com/25179620/104273324-acf6f900-546c-11eb-8bc0-7f2902d37a17.png)

**Comment by MartijnR** [comment]
* [ ] reproduce in enketo-core

**Comment by MartijnR** [comment]
The cause is that the count is not `num1` directly but an intermediate pyxform-added calculation for `repeat1_count` (which simply copies the `num1` value). This `repeat1_count` node is not present in the record to be edited and calculations are disabled in note-only and readonly modes which prevents it from being re-calculated to "correct" the absence of `repeat1_count`. 

The proper solution would be to store `repeat1_count` in OC and add it to the record to be edited.

* [ ] check if OC creates a fieldsubmission for repeat1_count

**Comment by MartijnR** [comment]
So this should be fixed on the OC side.

**Comment by pbowen-oc** [comment]
This is working for us now.
