### ISSUE TITLE
IE11/Edge Legacy - Choice Filter items not working correctly

### ISSUE THREAD

**Issue by pbowen-oc** [OpenClinica/enketo-express-oc#426]
IE11 / Edge Legacy only:

Form with choice filter select_one items is not displaying choice options correctly for the items using the choice filter.

In the attached form ( [edge_ie11_choicefilter.xml.txt](https://github.com/OpenClinica/enketo-express-oc/files/5818492/edge_ie11_choicefilter.xml.txt) ), the user can select a choice in the first item. If the user selects the first or second choice, it should cause some choices to be available in the second item's dropdown. However, the second item has no choices visible.

The form has a second set of items using the same logic, but as autocomplete items. In this case, selecting the first or second choice in the first item does allow choices to appear in the second item. However, upon selecting one, the choice name (not label) is displayed for the second item.

IE11:
![IE11 choice filter](https://user-images.githubusercontent.com/25179620/104682689-47507a00-56c3-11eb-9d37-25c1608cc0ac.png)

Chrome (working as expected):
![Screenshot 2021-01-15 102051](https://user-images.githubusercontent.com/25179620/104745621-48fa5c00-571c-11eb-9f84-af1456033308.png)

**Comment by theywa** [comment]
Hi @MartijnR ~ I tried to inspect the element to look at its structure and looks like the script that will set the Dom menu is not working properly(CMIIW)
![error-empty-dropdown](https://user-images.githubusercontent.com/13865076/104712056-b75b1080-5754-11eb-9cea-41fbdc74519e.png)
Empty option

![error-showing-value](https://user-images.githubusercontent.com/13865076/104712182-d5c10c00-5754-11eb-9df4-1e68c27e83e9.png)
A wrong option value set

Do you have any clue or maybe have a guess about which files that potentially caused it? 
Thanks

**Comment by MartijnR** [comment]
Hi @theywa,

This can really only be troubleshooted in Enketo Core I think (if there is no exception in the console). It might be a combination of issues. Not sure. Datalist stuff is done here: https://github.com/enketo/enketo-core/blob/master/src/widget/select-autocomplete/autocomplete.js. I would create a minimal form first in XLSForm (not using the OC form builder).

Cascading selections are done here: https://github.com/enketo/enketo-core/blob/master/src/js/itemset.js

We normally don't want any specific IE11/Edge Legacy code (changes) in Enketo Core, so hopefully the fix can be added to enketo-express-oc once you figure out what is going on.

**Comment by theywa** [comment]
Yes, the problem is on enketo-core in widgets-controller.js. This issue only happens when the form is loaded from OpenClinica(Study Runner) and can't reproduce it from enketo-express-oc locally(because some problem running enketo-core locally on virtual box, I use enketo-express-oc and put some debug on it's enketo-core in node_modules). Tried to copy the OC form's URL and open it without using iframe but the bug still exists.

The widgets on the form(loaded from OC) looks like this
![study-runner-wc-init-widgets](https://user-images.githubusercontent.com/13865076/105060300-ccb0a180-5aaa-11eb-9f84-2276311bcbd9.png)

And the widgets on form(loaded from enketo-express-oc) looks like this
![Enketo-express-oc-wc-init-widgets](https://user-images.githubusercontent.com/13865076/105060427-fbc71300-5aaa-11eb-93e8-d97a405eeb8a.png)

Both of them using the same XLS file and the URL looks the same (https://enketo-express-oc/single/fs/c/i/c3330a02e9b4b5bf524a86238eca83bf?ecid=a) also captured it on the legacy edge inspect element's console.  That screenshot comes from debugging in init function on widgets-controller.js. Not sure why the widget from OC looks like that, but because of that 
`new Collection( this ).update( Widget );` 
the code above after onChangeOption triggered failed to call the update method on DesktopSelectpicker Class(select-dekstop/selectpicker.js) that would reset the picker( `<ul class="dropdown-menu" role="menu"></ul>` )

 @MartijnR, do you have any thought about that? Any help is appreciated, thank you

**Comment by MartijnR** [comment]
The `Collection` is using WeakMap. But I would expect an exception to occur if this is not supported, or not polyfilled, in IE11 or Edge Legacy. So that's probably not it.

Maybe this issue is an issue with terser (minification). This would explain the difference you're seeing locally (since terser doesn't run when using `grunt develop-ie11`. Try disabling terser to load the unminified javascript.

However, we do run terser for modern browsers as well, so it could be some preceding IE11/Edge-Legacy build step that causes terser to change the class names.

**Comment by MartijnR** [comment]
This is supposed to prevent terser from changing class names: https://github.com/OpenClinica/enketo-express-oc/blob/master/Gruntfile.js#L181

**Comment by MartijnR** [comment]
Ah, I guess this doesn't work because after Babel's manipulation, these are no longer recognized as classes. There may be some other terser setting you can use for the old-browser build, and if not disable minification entirely (which will make that build even more excruciatingly slow).

**Comment by MartijnR** [comment]
> some other terser setting you can use for the old-browser build

Yes, see `--keep-fnames`: https://github.com/terser/terser

You could create a separate grunt task with that option and only use it for the old-browser build.

**Comment by theywa** [comment]
@MartijnR  ~ thank you, I test your suggestion and it really fixed the issue. Should I replace the 'build-ie11' instead of creating a new task?

**Comment by theywa** [comment]
@MartijnR ~ I found the workaround for this issue and revert the terser back to one only. I'll merge it first, please review it again when you have time, thank you.

**Comment by MartijnR** [comment]
hi @theywa, that's an interesting find!

This may break things if the selector of two different widgets is the same. However, that may currently not be the case, so seems fine.

I would put it in the js-ie11 task only, to follow our approach of keeping modern browser builds unaffected by IE11/EdgeLegacy workarounds.

**Comment by theywa** [comment]
@MartijnR ~ yes, I also have a doubt about that. But it looks like the selector is unique for each widget, right? 
also, should I update the Gruntfile task like this?
`grunt.registerTask( 'js', [ 'shell:clean-js', 'widgets', 'shell:rollup' ] );`
`grunt.registerTask( 'js-ie11', [ 'replace:widgets-controller', 'js', 'shell:polyfill-ie11', 'shell:babel-ie11', 'shell:browserify-ie11' ] );`
or also add another replace to undo the change on widgets-controller on JS's task?

**Comment by MartijnR** [comment]
Yes, I believe all selectors used by OC are different atm, so that's good.

Good point about undoing. I actually hadn't realized the source file was changed by this task. Could you make the change on the ie11-bundle instead (either after babel or browserify)? That way you won't have to undo anything and keep source files unchanged. I think "Widget.name" replacement should be safe if done before terser (I searched enketo-express-oc and enketo-core, and it only occurs in widgets-controller.js).

**Comment by theywa** [comment]
Got it, I create the PR

**Comment by pbowen-oc** [comment]
Looks good in testing.
