### ISSUE TITLE
Edge Legacy - Repeating group starts with extra repeat that is a duplicate of the first repeat

### ISSUE THREAD

**Issue by pbowen-oc** [OpenClinica/enketo-express-oc#427]
Edge Legacy only:

In the attached form ( [edge_repeats.xml.txt](https://github.com/OpenClinica/enketo-express-oc/files/5818517/edge_repeats.xml.txt) ), the form first opens with two repeats showing despite not using repeat count. When we enter data into the first repeat and then the second repeat, the data from the second repeat is submitted back as data for the first repeat (overwriting that on our end). When we add a repeat manually, the data for that is submitted back as data for the 3rd repeat. So, the form is showing 3 repeats at that point, but treating them as having ordinals 1, 1, and 3 (no ordinal 2).

Expected:
Form starts with only 1 repeat showing and each repeat has distinct ordinals.

**Comment by MartijnR** [comment]
Should be investigated in Enketo Core with a minimal (1 question) form.

**Comment by theywa** [comment]
@MartijnR  ~ after debugging, I think XPathResult is the one that caused this issue. So that 'getTemplateNodes' function does not return the correct array of the template to be removed. Still trying to find a polyfill or workaround for it.

**Comment by MartijnR** [comment]
Oh, I thought, since we saw that the comment was added correctly `<-- repeat://path/to/repeat -->` that `getTemplateNodes` was performing as expected and at least part of `addTemplate` too.

If getTemplateNodes is the problem the issue is probably the namespace (jr:template). I'll have a look if that expression was changed at some point.

**Comment by MartijnR** [comment]
Yes, in this performance-improvement commit...: https://github.com/enketo/enketo-core/commit/97c2e36e602742291abf77bfe657e6ee1b7e4935.

For now let me revert this in the enketo-core `5.16.16-oc` branch and then you can test it in enketo-express-oc. I'll add it on top of my other PR.

* [ ] martijn to add commit to enketo-core branch and create a PR for enketo-express-oc to review
* [ ] @theywa to review enketo-express-oc PR
* [ ] if this is a fix, martijn to merge into enketo-express-oc master branch and tag it, otherwise back to the drawing board..

**Comment by MartijnR** [comment]
Here you go @theywa: https://github.com/OpenClinica/enketo-express-oc/pull/433

**Comment by pbowen-oc** [comment]
@MartijnR - The fix here worked for us. Is there more to do with this to improve performance?

**Comment by MartijnR** [comment]
Yes, I believe the [fix](https://github.com/enketo/enketo-core/commit/2609a662882fa14a98bb4581a51199d8dc856923) can be reverted (since it only affected an obscure Edge Legacy version, which will improve performance.

* [ ] revert

**Comment by pbowen-oc** [comment]
@MartijnR - Was this already reverted in tag 2.8.0.oc-9?
