### ISSUE TITLE
Repeating group logic always referring to first occurrence for query status

### ISSUE THREAD

**Issue by pbowen-oc** [OpenClinica/enketo-express-oc#446]
When a constraint or required error appears on an item within a repeating group, the error message is only being cleared by adding a query to the item in the first occurrence of the repeating group (not the occurrence that the error message is in). I think the comment-status() function is always looking at the first repeat rather than the repeat that the item in question belongs to.

Steps:
1. Open the attached form - [repeat group query status.xml.txt](https://github.com/OpenClinica/enketo-express-oc/files/5940571/repeat.group.query.status.xml.txt)
2. Add a second repeating group
3. Enter a value >= 10 in the item in the second repeat so that the constraint fires
4. Add a query to the item in the second repeat

Expected:
The constraint message disappears.

Actual:
The constraint message remains.

Steps (continued)
5. Add a query to the item in the first repeat
6. Add a third repeating group
7. Enter a value >= 10 in the item in the third repeat so that the constraint fires

Expected:
The constraint message is shown for the item in the third repeat.

Actual:
No constraint message is shown for the item in the third repeat.

**Comment by MartijnR** [comment]
I believe the issue is with the XForm in the constraint logic that OC dynamically adds. 

The constraint condition contains segments like this:

```
comment-status(/data/rg1/int1_comment)='new'
```

`/data/rg1/int1_comment` will always return the first int_comment (now that we removed an odd deviation from the XForms spec and gave new XForms the attribute `odk:xforms-version="1.0.0"` to indicate to Enketo that it can evaluate these expressions properly now.

It should be (I think):

```
comment-status(../int1_comment)='new'
```

I believe this change could be made regardless of whether the question is inside a repeat or not. If OC always adds the query question as a sibling of the question it is linked with this fix on the OC side could be very easy, I think.

However, let me first confirm that what I wrote is correct.

* [ ] Martijn to confirm that the above is correct

**Comment by MartijnR** [comment]
http://localhost:8005/single/fs/i/VfKXzBGc?ecid=1

**Comment by pbowen-oc** [comment]
@MartijnR - Thanks. Is this just needed for the comment-status(/data/rg1/item1_comment) functions (changing to comment-status(../item1_comment) )? Or is it also needed for the bind that links the comment to the item: bind enk:for="/data/rg1/item1" nodeset="/data/rg1/item1_comment" ?

**Comment by MartijnR** [comment]
Only required for the `comment-status` parameters.

**Comment by pbowen-oc** [comment]
@MartijnR - We are in the process of making the change you recommended.

Are you saying that something was change on the Enketo side for how these references are evaluated? I just want to check since I see that we have forms in Production that use absolute references in the comment status and they work as expected. If something has changed, is there anything we should look out for in testing to ensure that general logic is evaluating as expected?

**Comment by MartijnR** [comment]
>  is there anything we should look out for in testing to ensure that general logic is evaluating as expected?

Enketo hasn't changed how it runs old forms. The change is in forms that were generated in recent versions of pyxform. Enketo can tell the difference between them by looking at the odk;xforms-version attribute.

The change I proposed above is merely correcting an incorrect XPath usage. This will work in both old and new forms, but I understand you'd only make the change in new forms, which is fine.

**Comment by pbowen-oc** [comment]
Thanks, @MartijnR. This is working as expected for us with the update you proposed.
