### ISSUE TITLE
Item calculated on form load, then becomes irrelevant but is not cleared

### ISSUE THREAD

**Issue by pbowen-oc** [OpenClinica/enketo-express-oc#451]
Steps:
1. Load the attached form ( [eligsmall.xml.txt](https://github.com/OpenClinica/enketo-express-oc/files/5999618/eligsmall.xml.txt) ) with attached clinicaldata ( [eligsmall.clinicaldata_instance.txt](https://github.com/OpenClinica/enketo-express-oc/files/5999619/eligsmall.clinicaldata_instance.txt) ) instance
2. Enter a date in the date item
3. Close or Complete the form

Expected:
Form Closes/Completes without error.

Actual:
There is a message that there are errors on the form. If the user is closing the form and chooses to continue, autoqueries are added to the first two items on the form. These items were initially calculated to "missing" before the cross-form data was read in. Once the cross-form data was read in, they became irrelevant, but the values in them were not cleared as expected.

![Screenshot 2021-02-17 203548](https://user-images.githubusercontent.com/25179620/108291527-6b8af500-7160-11eb-9189-71b3a470106f.png)

**Comment by MartijnR** [comment]
http://localhost:8005/single/fs/i/VF6g4UUe?ecid=1

**Comment by MartijnR** [comment]
@pbowen-oc, this is a difficult issue. Not sure how to fix it yet, so don't expect a fix shortly.

Clearing doesn't work for values that were set during loading but then immediately become non-relevant before loading completes. It only works if a group or question becomes non-relevant after loading completes. It's an edge case.

It helps a bit to provide form building guidance to not set default values ('missing' in this case) with a calculation but use a static default instead. This form would still have a remaining issue with `status_text` though.

**Comment by pbowen-oc** [comment]
@MartijnR - Thank you for the update. This case worked as desired prior to the latest release. Can you go back to the old method that was in use to handle cases like this?

By when loading completes, do you mean when all calculations have run? 

In this case, the form logic is not meant to set "missing" as a default. It is meant to set "missing" if the external data it is looking for is not present (which would then inform the user that the current form is not ready for data entry yet because prior steps have not been taken).

**Comment by MartijnR** [comment]
>this case worked as desired prior to the latest release
ok
> Can you go back to the old method that was in use to handle cases like this?
not without re-introducing the bugs that were fixed by re-designing the relevancy logic, I'm afraid
>By when loading completes, do you mean when all calculations have run?
when everything has run and the form is ready for the user to enter data
>not meant to set "missing" as a default.
Not finding a pulldata result in the clinicaldata or not having run the clinicaldata calculation yet, both result in `''`. So it's the same as a default, I think.

**Comment by pbowen-oc** [comment]
Upon thinking of this case and alternatives further, even if using a default value bypassed this case, I don't think "missing" would be appropriate as a default. I think the form would work correctly the first time it is opened if "missing" were defined as a default rather than a calculation result. However, if the form initially opened with the external source data in a non-"missing" state, it would then be unable to properly respond to a change in the source data if the form were subsequently re-opened (so it would break if the external data were not empty the first time but were empty the second time through).

**Comment by MartijnR** [comment]
Pasting email question here, to keep everything together in one thread.

> One thing I'm not sure I understand is how the calculations are evaluated at form load. Assuming no default values are set, 
are all the calculations essentially evaluated simultaneously while all the items are still null? And then any calculations whose dependencies have changed would recalculate?

One by one, never simultaneous and never asynchronous. And yes, dependent calculations would recalculate immediately (also during form load). The issue occurs due to relevancy changing from relevant to non-relevant during form load counterintuitively due to the order in which calculations are evaluated. Ideally, the order would become entirely predictable by evaluating everything in (XLS/XForm) order. That would solve other things and clean up the code significantly. It is however, [a difficult project](https://github.com/enketo/enketo-transformer/issues/73).

> missing
Yes, good point, about re-opening an existing record with missing external data. That's true.

**Comment by MartijnR** [comment]
If everything has a form control, the order would be predictable. That may offer a workaround.

**Comment by MartijnR** [comment]
This is an attempt to create an as-simple-as-possible example to illustrate the problem.

type | name | label | calculation | relevant | default
-- | -- | -- | -- | -- | --
text | status |   | 1 |   | default
text | status_show | Status: | ${status} | ${status} != 1 |  

[xlsform](https://docs.google.com/spreadsheets/d/1IoxeNWpmwZhKy-SRinD_4DbfUespJNZHfOVu3ndkX6k/edit?usp=sharing)

What we see in Enketo currently when loading has completed:

```xml
<data>
    <status>1</status>
    <status_show>default</status_show>
</data>
```
What happens is:
1. calculation for `status_show` is conducted, value is set to `default`, because it is relevant
2. calculation for `status` is conducted and value is set to `1`
3. `status_show` is not re-calculated because it is no longer relevant

What we would see if the order of evaluation made sense is:

```xml
<data>
    <status>1</status>
    <status_show/>
</data>
```

And the latter is what we see if we give the first question a label so it becomes a form control, because the following happens:

1. calculation for `status` is conducted, value is set to `1`.
2. `status_show` is never calculated because is not relevant. Value remains empty.

I think the before-mentioned _difficult project_ has to be implemented for this to start working (and not break again). It would also greatly help other developers make sense of Enketo's engine (and also help with #247) as the evaluation order becomes logical and Enketo's engine will become much simpler. It's hard to estimate how long it will take. Initial work maybe not so long (40-80 hrs), but the question is how many things will break that are not caught by automated tests.

**Comment by pbowen-oc** [comment]
@MartijnR - In that possible new methodology you described, what would happen if we open the record with a value already in `status_show` ? For example, suppose the record is being opened under a different form definition and the relevant logic on that item is different than it was previously when a value had been calculated (or data had been inserted from another source before opening the form in Enketo)? 

What we're looking for is the same behavior on form open as would occur if during form data entry the calculated item became non-relevant - i.e., clear the calculated value and allow the item/group to be non-relevant without error.

**Comment by MartijnR** [comment]
`status_show` would still not be emptied... so yeah the problem would only be 1/3 solved...

The  2nd issue in OC's fork only (I just realized) is that readonly questions shouldn't really get a relevant error, right? They do currently and that is actually the reason the Close button prompts the alert and adds those queries. That could be fixed.

The 3rd issue in OC's fork only is that a group and perhaps individual questions that for some reason have values upon load but are non-relevant once the loading completes, are never emptied. That should be fixable, but for some reason, I haven't succeeded yet.

**Comment by MartijnR** [comment]
Note to self: 

The reason I've been stuck with the 3rd issue is that because of the 1st issue, the values are cleared from the view, but not from the model, during initialization. Calling `form.clearNonRelevant` after form initialization therefore doesn't trigger the change event in `input.setVal` (an important performance optimization and also required for dn query audits), because the view doesn't change. Hence the model values are never cleared.

When looking at calculate.js this same problem doesn't occur it sets the model values itself. Very inconsistent approaches. Should be re-designed as well. Consider setting the model value explicitly and not passing any event parameters to `input.clear`. Or perhaps just inputUpdate as there may be logic that needs to re-evaluated upon clearing.

**Comment by pbowen-oc** [comment]
@MartijnR - For the 2nd issue, I think that with the previous behavior of clearing read-only items that were not relevant, then there wasn't really a case for a read-only items to have a value and also be non-relevant. The alert on Close and autoqueries are the symptom that is most acute for us now as it really impacts form usage, but the the value is intended to be submitted back to us when it is cleared. Without clearing and submitting the value, the old value will persist in our DB and also be sent back with the form next time it is opened. That may not be a particular issue on the form itself if the errors are removed. 

If we can get the errors/autoquery prompts removed, I think that would alleviate most of the issues we are facing.

**Comment by MartijnR** [comment]
@pbowen-oc, @svadla-oc This is ready for testing and tagged in master as `2.5.6.oc-6`.

The remaining issue is that the values 'missing' should never be set, but at least this is now corrected afterwards, by removing those values.

**Comment by pbowen-oc** [comment]
Thanks! We will start testing ASAP.

**Comment by pbowen-oc** [comment]
@MartijnR - In the attached form ( [Issue 451 test non-calculate.xml.txt](https://github.com/OpenClinica/enketo-express-oc/files/6025710/Issue.451.test.non-calculate.xml.txt) ), if the form is opened in review-only mode with a value in item2 but item2 non-relevant (such item1 being null), that value is being cleared and submitted. The expectation is that no item data will change in review-only mode.

**Comment by MartijnR** [comment]
```bash
curl --user enketorules: -d "server_url=http://localhost:3000&form_id=issue.451.test.non-calculate&ecid=1&instance=<data><item_2>something</item_2></data>&instance_id=a" http://localhost:8005/oc/api/v1/instance/note
```

**Comment by MartijnR** [comment]
ready for testing @pbowen-oc

**Comment by pbowen-oc** [comment]
Looks good in testing.
