### ISSUE TITLE
Issue With Printing Single Select Items with Minimal Display on Chrome and Edge

### ISSUE THREAD

**Issue by theywa** [OpenClinica/enketo-express-oc#456]
Single select items with minimal display do not print correctly on Chrome and Edge.
![Screenshot from 2021-02-24 21-31-23](https://user-images.githubusercontent.com/13865076/109015416-adc7af80-76e7-11eb-9cf8-c39fa6087722.png)

**Comment by theywa** [comment]
@MartijnR ~ I'm not sure why the print mess up on chrome and edge and not on firefox. tried to look at it but still not found the issue. It just the calculated height on Chrome is not correct. And by removing that calculate height on minimal display actually solved the issue, but that fix should be done in the enketo-core. 
I'm using this xls for testing 

[Minimal Forms version 2.zip](https://github.com/OpenClinica/enketo-express-oc/files/6050468/Minimal.Forms.version.2.zip)

**Comment by MartijnR** [comment]
Note for self: http://localhost:8005/?xform=Minimal-Forms-version-2.xml

**Comment by MartijnR** [comment]
@theywa, is there a special way you've found to reproduce this issue? Tried both enketo-core (using `printGridView()` in console) and enketo-express-oc (using Print button) in Chrome on Mac OS, but I have not been able to.

**Comment by theywa** [comment]
@MartijnR ~ I'm using /preview like https://dewa.ngrok.io/preview?form=https://dewa.ngrok.io/minimal-form.xml

https://user-images.githubusercontent.com/13865076/109616038-3e2e4600-7b67-11eb-9a20-4a68ec39228f.mp4

for some reason, the print preview on chrome looks different compared to Mozilla 
on demo above I comment the DePrintify and styleReset script so the page is not reset back after canceling the print.

**Comment by MartijnR** [comment]
Thanks @theywa. I cannot reproduce this myself, which makes me think it's a timing issue and relates to CPU speed (tried throttling CPU in dev console but that didn't work which may be because it's not the speed of the script execution but some internal repainting). 

If you can consistently reproduce this can you please try adjusting the various print timings to see if that provides an alternative fix? 

https://github.com/OpenClinica/enketo-express-oc/blob/master/public/js/src/module/gui.js
https://github.com/enketo/enketo-core/blob/master/src/js/print.js

The problem with the fix you created is that it actually causes problems if the question is adjacent to another question. We already realized that back when that same fix was used for an image-map widget, but figured nobody would find out because nobody would put another question next to an image-map. With a minimal select it is very likely that this will be done and therefore that fix may create more issues than it solves.

**Comment by theywa** [comment]
Hi @MartijnR, sorry for the late response. I tried the suggestion but it's not fixed the issue, but by adding new timing/delay after styleToAll() it fixed the issue, somehow chrome takes longer to apply the new style so the calculation is not right. Do you think this fixed is safe?

**Comment by MartijnR** [comment]
Yes, that should be safe. Too bad we couldn't put the fix in `printOcForm` instead (to minimize changes in enketo/enketo-express), but maybe we'll have to apply the same fix in enketo-express some day (I'll wait until somebody runs into this I think).

**Comment by pbowen-oc** [comment]
Looks good in testing.
