### ISSUE TITLE
SVG Image Map not appearing in Offline forms

### ISSUE THREAD

**Issue by Apotischman** [OpenClinica/enketo-express-oc#542]
**Describe the bug**
An SVG Image map is not appearing in Offline mode. It does work for both Online and single/fs/c/i

**To Reproduce**
Steps to reproduce the behavior. If applicable please include the smallest possible XLSForm or XForm (as zip or link).

1. Load a form in Offline mode that is configured with a SVG Image
2. Notice that the image is not appearing.

I was unable to get the XForm from the offline form. I had to pull from another environment. It should be close.
[Map_XForm.txt](https://github.com/OpenClinica/enketo-express-oc/files/8326734/Map_XForm.txt)

**Expected behavior**
The image should appear on load. This is working correctly in both Online and single/fs/c/i modes.

**Screenshots**
I was unable to get a screenshot of it not working due to some current issues. The attached screenshot is from single/fs/c/i.

![single_fs](https://user-images.githubusercontent.com/87195434/159544061-6edb958b-6b89-4cad-a1cf-8a80508a7235.png)

Screenshot of the map missing
![NoMap](https://user-images.githubusercontent.com/87195434/159784329-026297c3-2de9-4d69-ab20-f07d29983837.png)

**Browser and OS (please complete the following information):**

-   OS: [e.g. iOS]
-   Browser: Chrome

**Additional context**

**Comment by MartijnR** [comment]
possibly only occurs with widget on non-first page

**Comment by MartijnR** [comment]
headers sent when working:
```
{
      date: 'Fri, 25 Mar 2022 20:35:25 GMT',
      'content-type': 'image/svg+xml',
      'content-length': '31768',
      connection: 'close',
      vary: 'Accept-Encoding, Accept-Language, Cookie, Origin',
      'content-disposition': 'attachment; filename=US_MAP.svg',
      allow: 'GET, HEAD, OPTIONS',
      'x-frame-options': 'DENY',
      'content-language': 'en',
      'strict-transport-security': 'max-age=15724800; includeSubDomains'
    }
```

**Comment by MartijnR** [comment]
I was able to reproduce it (or a different issue that manifests the same...) by serving the SVG file with an incorrect `'text/xml'` Content-Type. Fixing that on the form server, fixed the issue. However, when the issue occurs the SVG file is stored in the browser database incorrectly. Fixing the Content-Type won't cause this stored file (for that particular form) to be refreshed. Easiest way to force that to happen is to use the Clear Storage button.

The online-only version tolerates an incorrect content-type but the offline-capable view doesn't. This has to do with how the file is served (as a local blob from the database in an offline-capable view).

To check if the issue you experienced has the same cause (since you're using a different server) or to check whether the OC server has been fixed:

1. go to the online-only view of the form, and look at the network tab in the developer tools
2. the third column (Type) for the SVG request should say 'svg+xml' and not 'text/xml'

**Comment by pbowen-oc** [comment]
@MartijnR - Thanks. I checked what it is doing now and the call for the image map has type listed as "fetch" and there is no Content-Type listed in the headers. The Print icon call does have type as "svg+xml" as you were expecting. Am I correct in thinking "fetch" is a different case of the same invalid Content-Type as you suggested?

**Comment by MartijnR** [comment]
@pbowen-oc ignore the fetch requests. There should be matching request for the same resource. This fetch request seems to be a new thing in Chrome. Not sure what purpose it serves yet.

**Comment by pbowen-oc** [comment]
@MartijnR - The only request I'm seeing for this file now is "fetch". I compared it to another environment without our latest changes and it is being sent as "svg+xml" there, so it looks like something has changed on our end.

**Comment by pbowen-oc** [comment]
Confirmed that this was an issue with our requests.
