### ISSUE TITLE
"analog-scale vertical show-scale" only allows selecting by 10

### ISSUE THREAD

**Issue by Apotischman** [OpenClinica/enketo-express-oc#603]
**Describe the bug**
When a user is accessing an integer item using appearance "analog-scale vertical show-scale", they are only allowed to select numbers in increments of 10.

**To Reproduce**
Steps to reproduce the behavior. If applicable please include the smallest possible XLSForm or XForm (as zip or link).

[Xform_analog_scale.txt](https://github.com/OpenClinica/enketo-express-oc/files/10170057/Xform_analog_scale.txt)

**Expected behavior**
If the scale is between 1 and 100, I should be able to select any number. Instead, I can only select 10,20,30,etc

**Screenshots**

**Additional context**
The scale works properly if the item is configured as:
analog-scale vertical no-ticks
analog-scale vertical
analog-scale horizontal
analog-scale horizontal no-ticks

**Comment by MartijnR** [comment]
http://localhost:8005/single/fs/i/cbR1CpEV?ecid=1

**Comment by MartijnR** [comment]
This was the original implementation of the analog scale widget with `integer` and `decimal` question types. The values for min, max and step are hardcoded for these types. We've since implemented a more flexible widget that builds upon the `range` question type. The old implementation was maintained for backwards compatibility's sake (and has remained unchanged, I think).

So using the same appearances but tweaking step, min and max would be the best solution in this case (and probably discouraging the use of integer and decimal types for analog scale questions): https://xlsform.org/en/#range

**Comment by pbowen-oc** [comment]
@MartijnR - We'll retest this on the latest build. The previous behavior was that we could select any integer from 0-100 with an integer item using this appearance. We have not used the range widget yet, so our existing forms are all using this as integer items.

**Comment by MartijnR** [comment]
The likely change (Aug 28th, 2020): https://github.com/enketo/enketo-core/commit/0292b83453129316ba03850ab07d9e857a6f85b1

* [ ] check showScale behavior

**Comment by pbowen-oc** [comment]
@MartijnR - Yes, we'd like the user to be able to select in single integer increments, but still show the scale in units of 10.

**Comment by MartijnR** [comment]
https://github.com/enketo/enketo-core/issues/950
