### ISSUE TITLE
Reversing PRs in master leads to messy git history

### ISSUE THREAD

**Issue by MartijnR** [OpenClinica/enketo-express-oc#707]
Somehow we're back at 6.0.0? 

I think it is best not to revert merges in `master` if you find bugs @kkrumlian. Simply deploy a previous commit instead but leave master as-is.

**Comment by kkrumlian** [comment]
So here's the situation 
- After a merge we run smoke tests. If the smoke tests fail we are usually need to revert. Because if we don't revert we start seeing failures within our stack. 

Based on your message and our requirements this is what i'm thinking: 
- Before merging anything into master either (create a branch or merge into a pre-existing branch or a tag) 
- Merge PRs into master
- If issues with master I can always deploy from branch or tag and leave master as is and fail forward. 

As for the current state: 
- I do have a branch without the reverts: https://github.com/OpenClinica/enketo-express-oc/tree/master-latest-external-upstream
- I can rename current master branch to something else and rename the master-latest-external-upstream to master

@MartijnR  let me know if the above sounds good and will move forward!

**Comment by MartijnR** [comment]
> I can rename current master branch to something else and rename the master-latest-external-upstream to master

Yes, that seems like a good idea. That branch still has a clean history. Please do. You may have to change the Default Branch in the [repo settings](https://github.com/OpenClinica/enketo-express-oc/settings), as they may point to the renamed master automatically. Similarly, I'm not sure what git does e.g. on your dev server that has pulled a different master, but it seems like that can be figured out.

> If issues with master I can always deploy from branch or tag and leave master as is and fail forward.

Or just the commit before the merge.

As for the smoke test, would it be possible to run those on the PR branch before merging? It would be even cooler if that could be automated in a GitHub action, as part of the PR-checks that need to pass before merging is allowed.

**Comment by kkrumlian** [comment]
Closing this issue. We should be all reverted back.
